package model;
// Generated Mar 25, 2014 6:54:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rumah generated by hbm2java
 */
@Entity
@Table(name="rumah"
    ,catalog="rtrw"
)
public class Rumah  implements java.io.Serializable {


     private Integer id;
     private Character blokRumah;
     private Integer nomorRumah;
     private Integer kepalaKeluargaId;
     private String telp;
     private String handphone;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public Rumah() {
    }

    public Rumah(Character blokRumah, Integer nomorRumah, Integer kepalaKeluargaId, String telp, String handphone, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.blokRumah = blokRumah;
       this.nomorRumah = nomorRumah;
       this.kepalaKeluargaId = kepalaKeluargaId;
       this.telp = telp;
       this.handphone = handphone;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="BLOK_RUMAH", length=1)
    public Character getBlokRumah() {
        return this.blokRumah;
    }
    
    public void setBlokRumah(Character blokRumah) {
        this.blokRumah = blokRumah;
    }

    
    @Column(name="NOMOR_RUMAH")
    public Integer getNomorRumah() {
        return this.nomorRumah;
    }
    
    public void setNomorRumah(Integer nomorRumah) {
        this.nomorRumah = nomorRumah;
    }

    
    @Column(name="KEPALA_KELUARGA_ID")
    public Integer getKepalaKeluargaId() {
        return this.kepalaKeluargaId;
    }
    
    public void setKepalaKeluargaId(Integer kepalaKeluargaId) {
        this.kepalaKeluargaId = kepalaKeluargaId;
    }

    
    @Column(name="TELP", length=20)
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }

    
    @Column(name="HANDPHONE", length=40)
    public String getHandphone() {
        return this.handphone;
    }
    
    public void setHandphone(String handphone) {
        this.handphone = handphone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


