package model;
// Generated Mar 25, 2014 6:54:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Warga generated by hbm2java
 */
@Entity
@Table(name="warga"
    ,catalog="rtrw"
)
public class Warga  implements java.io.Serializable {


     private Integer id;
     private Integer idRumah;
     private String nama;
     private Integer jenisKelamin;
     private Integer agama;
     private Integer statusPernikahan;
     private Integer statusDalamKeluarga;
     private String handphone;
     private String tempatLahir;
     private Date tanggalLahir;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public Warga() {
    }

    public Warga(Integer idRumah, String nama, Integer jenisKelamin, Integer agama, Integer statusPernikahan, Integer statusDalamKeluarga, String handphone, String tempatLahir, Date tanggalLahir, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.idRumah = idRumah;
       this.nama = nama;
       this.jenisKelamin = jenisKelamin;
       this.agama = agama;
       this.statusPernikahan = statusPernikahan;
       this.statusDalamKeluarga = statusDalamKeluarga;
       this.handphone = handphone;
       this.tempatLahir = tempatLahir;
       this.tanggalLahir = tanggalLahir;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ID_RUMAH")
    public Integer getIdRumah() {
        return this.idRumah;
    }
    
    public void setIdRumah(Integer idRumah) {
        this.idRumah = idRumah;
    }

    
    @Column(name="NAMA", length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="JENIS_KELAMIN")
    public Integer getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(Integer jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    
    @Column(name="AGAMA")
    public Integer getAgama() {
        return this.agama;
    }
    
    public void setAgama(Integer agama) {
        this.agama = agama;
    }

    
    @Column(name="STATUS_PERNIKAHAN")
    public Integer getStatusPernikahan() {
        return this.statusPernikahan;
    }
    
    public void setStatusPernikahan(Integer statusPernikahan) {
        this.statusPernikahan = statusPernikahan;
    }

    
    @Column(name="STATUS_DALAM_KELUARGA")
    public Integer getStatusDalamKeluarga() {
        return this.statusDalamKeluarga;
    }
    
    public void setStatusDalamKeluarga(Integer statusDalamKeluarga) {
        this.statusDalamKeluarga = statusDalamKeluarga;
    }

    
    @Column(name="HANDPHONE", length=40)
    public String getHandphone() {
        return this.handphone;
    }
    
    public void setHandphone(String handphone) {
        this.handphone = handphone;
    }

    
    @Column(name="TEMPAT_LAHIR", length=100)
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_LAHIR", length=19)
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


