package rtrw;
// Generated Mar 20, 2014 12:37:33 PM by Hibernate Tools 3.6.0



/**
 * Penduduk generated by hbm2java
 */
public class Penduduk  implements java.io.Serializable {


     private Integer id;
     private String nik;
     private String name;

    public Penduduk() {
    }

    public Penduduk(String nik, String name) {
       this.nik = nik;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


