package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ABankAccounts generated by hbm2java
 */
@Entity
@Table(name="A_BANK_ACCOUNTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ABankAccounts  implements java.io.Serializable {


     private int id;
     private Integer bankId;
     private Integer accountId;
     private String noRekening;
     private String namaPemilik;
     private Date created;
     private Date modified;

    public ABankAccounts() {
    }

	
    public ABankAccounts(int id) {
        this.id = id;
    }
    public ABankAccounts(int id, Integer bankId, Integer accountId, String noRekening, String namaPemilik, Date created, Date modified) {
       this.id = id;
       this.bankId = bankId;
       this.accountId = accountId;
       this.noRekening = noRekening;
       this.namaPemilik = namaPemilik;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="BANK_ID")
    public Integer getBankId() {
        return this.bankId;
    }
    
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="ACCOUNT_ID")
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    
    @Column(name="NO_REKENING", length=100)
    public String getNoRekening() {
        return this.noRekening;
    }
    
    public void setNoRekening(String noRekening) {
        this.noRekening = noRekening;
    }

    
    @Column(name="NAMA_PEMILIK", length=100)
    public String getNamaPemilik() {
        return this.namaPemilik;
    }
    
    public void setNamaPemilik(String namaPemilik) {
        this.namaPemilik = namaPemilik;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


