package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AutoAssignPm generated by hbm2java
 */
@Entity
@Table(name="AUTO_ASSIGN_PM"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class AutoAssignPm  implements java.io.Serializable {


     private int id;
     private Integer areaId;
     private Integer groupCustomerId;
     private Integer userId;

    public AutoAssignPm() {
    }

	
    public AutoAssignPm(int id) {
        this.id = id;
    }
    public AutoAssignPm(int id, Integer areaId, Integer groupCustomerId, Integer userId) {
       this.id = id;
       this.areaId = areaId;
       this.groupCustomerId = groupCustomerId;
       this.userId = userId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="AREA_ID")
    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    
    @Column(name="GROUP_CUSTOMER_ID")
    public Integer getGroupCustomerId() {
        return this.groupCustomerId;
    }
    
    public void setGroupCustomerId(Integer groupCustomerId) {
        this.groupCustomerId = groupCustomerId;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


