package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bast generated by hbm2java
 */
@Entity
@Table(name="BAST"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Bast  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Date received;
     private Date submited;
     private String remark;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modiified;

    public Bast() {
    }

	
    public Bast(int id) {
        this.id = id;
    }
    public Bast(int id, Integer projectId, Date received, Date submited, String remark, Integer userCreated, Integer userModified, Date created, Date modiified) {
       this.id = id;
       this.projectId = projectId;
       this.received = received;
       this.submited = submited;
       this.remark = remark;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modiified = modiified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECEIVED", length=23)
    public Date getReceived() {
        return this.received;
    }
    
    public void setReceived(Date received) {
        this.received = received;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SUBMITED", length=23)
    public Date getSubmited() {
        return this.submited;
    }
    
    public void setSubmited(Date submited) {
        this.submited = submited;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIIFIED", length=23)
    public Date getModiified() {
        return this.modiified;
    }
    
    public void setModiified(Date modiified) {
        this.modiified = modiified;
    }




}


