package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boq generated by hbm2java
 */
@Entity
@Table(name="BOQ"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Boq  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer nilaiBoq;
     private Integer nilaiBoqTerpasang;
     private String remark;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modified;

    public Boq() {
    }

	
    public Boq(int id) {
        this.id = id;
    }
    public Boq(int id, Integer projectId, Integer nilaiBoq, Integer nilaiBoqTerpasang, String remark, Integer userCreated, Integer userModified, Date created, Date modified) {
       this.id = id;
       this.projectId = projectId;
       this.nilaiBoq = nilaiBoq;
       this.nilaiBoqTerpasang = nilaiBoqTerpasang;
       this.remark = remark;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="NILAI_BOQ")
    public Integer getNilaiBoq() {
        return this.nilaiBoq;
    }
    
    public void setNilaiBoq(Integer nilaiBoq) {
        this.nilaiBoq = nilaiBoq;
    }

    
    @Column(name="NILAI_BOQ_TERPASANG")
    public Integer getNilaiBoqTerpasang() {
        return this.nilaiBoqTerpasang;
    }
    
    public void setNilaiBoqTerpasang(Integer nilaiBoqTerpasang) {
        this.nilaiBoqTerpasang = nilaiBoqTerpasang;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


