package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name="CALENDAR"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Calendar  implements java.io.Serializable {


     private CalendarId id;

    public Calendar() {
    }

    public Calendar(CalendarId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="bulan", column=@Column(name="BULAN", nullable=false) ), 
        @AttributeOverride(name="hari", column=@Column(name="HARI", nullable=false) ) } )
    public CalendarId getId() {
        return this.id;
    }
    
    public void setId(CalendarId id) {
        this.id = id;
    }




}


