package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendarId generated by hbm2java
 */
@Embeddable
public class CalendarId  implements java.io.Serializable {


     private int bulan;
     private int hari;

    public CalendarId() {
    }

    public CalendarId(int bulan, int hari) {
       this.bulan = bulan;
       this.hari = hari;
    }
   


    @Column(name="BULAN", nullable=false)
    public int getBulan() {
        return this.bulan;
    }
    
    public void setBulan(int bulan) {
        this.bulan = bulan;
    }


    @Column(name="HARI", nullable=false)
    public int getHari() {
        return this.hari;
    }
    
    public void setHari(int hari) {
        this.hari = hari;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalendarId) ) return false;
		 CalendarId castOther = ( CalendarId ) other; 
         
		 return (this.getBulan()==castOther.getBulan())
 && (this.getHari()==castOther.getHari());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBulan();
         result = 37 * result + this.getHari();
         return result;
   }   


}


