package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CorTbg generated by hbm2java
 */
@Entity
@Table(name="COR_TBG"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class CorTbg  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Date boqFinalActualDone;
     private Date actualDraftCor;
     private Date submitActualDone;
     private Date created;
     private Date modified;

    public CorTbg() {
    }

	
    public CorTbg(int id) {
        this.id = id;
    }
    public CorTbg(int id, Integer projectId, Date boqFinalActualDone, Date actualDraftCor, Date submitActualDone, Date created, Date modified) {
       this.id = id;
       this.projectId = projectId;
       this.boqFinalActualDone = boqFinalActualDone;
       this.actualDraftCor = actualDraftCor;
       this.submitActualDone = submitActualDone;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BOQ_FINAL_ACTUAL_DONE", length=23)
    public Date getBoqFinalActualDone() {
        return this.boqFinalActualDone;
    }
    
    public void setBoqFinalActualDone(Date boqFinalActualDone) {
        this.boqFinalActualDone = boqFinalActualDone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_DRAFT_COR", length=23)
    public Date getActualDraftCor() {
        return this.actualDraftCor;
    }
    
    public void setActualDraftCor(Date actualDraftCor) {
        this.actualDraftCor = actualDraftCor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SUBMIT_ACTUAL_DONE", length=23)
    public Date getSubmitActualDone() {
        return this.submitActualDone;
    }
    
    public void setSubmitActualDone(Date submitActualDone) {
        this.submitActualDone = submitActualDone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


