package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerContacts generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_CONTACTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class CustomerContacts  implements java.io.Serializable {


     private int id;
     private int customerId;
     private String name;
     private String noHandphone;
     private String email;
     private String jabatan;

    public CustomerContacts() {
    }

    public CustomerContacts(int id, int customerId, String name, String noHandphone, String email, String jabatan) {
       this.id = id;
       this.customerId = customerId;
       this.name = name;
       this.noHandphone = noHandphone;
       this.email = email;
       this.jabatan = jabatan;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CUSTOMER_ID", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NO_HANDPHONE", nullable=false, length=25)
    public String getNoHandphone() {
        return this.noHandphone;
    }
    
    public void setNoHandphone(String noHandphone) {
        this.noHandphone = noHandphone;
    }

    
    @Column(name="EMAIL", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="JABATAN", nullable=false, length=100)
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }




}


