package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerFp generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_FP"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class CustomerFp  implements java.io.Serializable {


     private int id;
     private String customerName;
     private String address;
     private String noNpwp;
     private String customerCode;
     private String addressInvoice;

    public CustomerFp() {
    }

	
    public CustomerFp(int id) {
        this.id = id;
    }
    public CustomerFp(int id, String customerName, String address, String noNpwp, String customerCode, String addressInvoice) {
       this.id = id;
       this.customerName = customerName;
       this.address = address;
       this.noNpwp = noNpwp;
       this.customerCode = customerCode;
       this.addressInvoice = addressInvoice;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CUSTOMER_NAME", length=100)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="NO_NPWP", length=100)
    public String getNoNpwp() {
        return this.noNpwp;
    }
    
    public void setNoNpwp(String noNpwp) {
        this.noNpwp = noNpwp;
    }

    
    @Column(name="CUSTOMER_CODE", length=50)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="ADDRESS_INVOICE")
    public String getAddressInvoice() {
        return this.addressInvoice;
    }
    
    public void setAddressInvoice(String addressInvoice) {
        this.addressInvoice = addressInvoice;
    }




}


