package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeliveryItemInfo generated by hbm2java
 */
@Entity
@Table(name="DELIVERY_ITEM_INFO"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class DeliveryItemInfo  implements java.io.Serializable {


     private int projectId;
     private Integer semen;
     private Integer besi;
     private Integer anchor;
     private Integer tower;
     private Integer me;
     private Integer civilfab;

    public DeliveryItemInfo() {
    }

	
    public DeliveryItemInfo(int projectId) {
        this.projectId = projectId;
    }
    public DeliveryItemInfo(int projectId, Integer semen, Integer besi, Integer anchor, Integer tower, Integer me, Integer civilfab) {
       this.projectId = projectId;
       this.semen = semen;
       this.besi = besi;
       this.anchor = anchor;
       this.tower = tower;
       this.me = me;
       this.civilfab = civilfab;
    }
   
     @Id 

    
    @Column(name="PROJECT_ID", unique=true, nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="SEMEN")
    public Integer getSemen() {
        return this.semen;
    }
    
    public void setSemen(Integer semen) {
        this.semen = semen;
    }

    
    @Column(name="BESI")
    public Integer getBesi() {
        return this.besi;
    }
    
    public void setBesi(Integer besi) {
        this.besi = besi;
    }

    
    @Column(name="ANCHOR")
    public Integer getAnchor() {
        return this.anchor;
    }
    
    public void setAnchor(Integer anchor) {
        this.anchor = anchor;
    }

    
    @Column(name="TOWER")
    public Integer getTower() {
        return this.tower;
    }
    
    public void setTower(Integer tower) {
        this.tower = tower;
    }

    
    @Column(name="ME")
    public Integer getMe() {
        return this.me;
    }
    
    public void setMe(Integer me) {
        this.me = me;
    }

    
    @Column(name="CIVILFAB")
    public Integer getCivilfab() {
        return this.civilfab;
    }
    
    public void setCivilfab(Integer civilfab) {
        this.civilfab = civilfab;
    }




}


