package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Departements generated by hbm2java
 */
@Entity
@Table(name="DEPARTEMENTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Departements  implements java.io.Serializable {


     private int id;
     private String name;
     private Date created;
     private Date modified;

    public Departements() {
    }

	
    public Departements(int id) {
        this.id = id;
    }
    public Departements(int id, String name, Date created, Date modified) {
       this.id = id;
       this.name = name;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFIED", length=10)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


