package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Documents generated by hbm2java
 */
@Entity
@Table(name="DOCUMENTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Documents  implements java.io.Serializable {


     private int id;
     private int customerId;
     private String name;
     private Integer status;
     private Integer parent;
     private Integer priority;
     private Integer documentTypeId;
     private Integer checkByProject;
     private Integer progressDetailId;
     private String nameAlias;
     private Integer subPriority;
     private Integer fromDepartementId;
     private Integer siteTypeId;
     private Integer term1;
     private Integer term2;
     private Integer term3;
     private Integer term4;

    public Documents() {
    }

	
    public Documents(int id, int customerId, String name) {
        this.id = id;
        this.customerId = customerId;
        this.name = name;
    }
    public Documents(int id, int customerId, String name, Integer status, Integer parent, Integer priority, Integer documentTypeId, Integer checkByProject, Integer progressDetailId, String nameAlias, Integer subPriority, Integer fromDepartementId, Integer siteTypeId, Integer term1, Integer term2, Integer term3, Integer term4) {
       this.id = id;
       this.customerId = customerId;
       this.name = name;
       this.status = status;
       this.parent = parent;
       this.priority = priority;
       this.documentTypeId = documentTypeId;
       this.checkByProject = checkByProject;
       this.progressDetailId = progressDetailId;
       this.nameAlias = nameAlias;
       this.subPriority = subPriority;
       this.fromDepartementId = fromDepartementId;
       this.siteTypeId = siteTypeId;
       this.term1 = term1;
       this.term2 = term2;
       this.term3 = term3;
       this.term4 = term4;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CUSTOMER_ID", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="PARENT")
    public Integer getParent() {
        return this.parent;
    }
    
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    
    @Column(name="PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    
    @Column(name="DOCUMENT_TYPE_ID")
    public Integer getDocumentTypeId() {
        return this.documentTypeId;
    }
    
    public void setDocumentTypeId(Integer documentTypeId) {
        this.documentTypeId = documentTypeId;
    }

    
    @Column(name="CHECK_BY_PROJECT")
    public Integer getCheckByProject() {
        return this.checkByProject;
    }
    
    public void setCheckByProject(Integer checkByProject) {
        this.checkByProject = checkByProject;
    }

    
    @Column(name="PROGRESS_DETAIL_ID")
    public Integer getProgressDetailId() {
        return this.progressDetailId;
    }
    
    public void setProgressDetailId(Integer progressDetailId) {
        this.progressDetailId = progressDetailId;
    }

    
    @Column(name="NAME_ALIAS")
    public String getNameAlias() {
        return this.nameAlias;
    }
    
    public void setNameAlias(String nameAlias) {
        this.nameAlias = nameAlias;
    }

    
    @Column(name="SUB_PRIORITY")
    public Integer getSubPriority() {
        return this.subPriority;
    }
    
    public void setSubPriority(Integer subPriority) {
        this.subPriority = subPriority;
    }

    
    @Column(name="FROM_DEPARTEMENT_ID")
    public Integer getFromDepartementId() {
        return this.fromDepartementId;
    }
    
    public void setFromDepartementId(Integer fromDepartementId) {
        this.fromDepartementId = fromDepartementId;
    }

    
    @Column(name="SITE_TYPE_ID")
    public Integer getSiteTypeId() {
        return this.siteTypeId;
    }
    
    public void setSiteTypeId(Integer siteTypeId) {
        this.siteTypeId = siteTypeId;
    }

    
    @Column(name="TERM1")
    public Integer getTerm1() {
        return this.term1;
    }
    
    public void setTerm1(Integer term1) {
        this.term1 = term1;
    }

    
    @Column(name="TERM2")
    public Integer getTerm2() {
        return this.term2;
    }
    
    public void setTerm2(Integer term2) {
        this.term2 = term2;
    }

    
    @Column(name="TERM3")
    public Integer getTerm3() {
        return this.term3;
    }
    
    public void setTerm3(Integer term3) {
        this.term3 = term3;
    }

    
    @Column(name="TERM4")
    public Integer getTerm4() {
        return this.term4;
    }
    
    public void setTerm4(Integer term4) {
        this.term4 = term4;
    }




}


