package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentState generated by hbm2java
 */
@Entity
@Table(name="DOCUMENT_STATE"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class DocumentState  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer priority;
     private Integer groupState;

    public DocumentState() {
    }

	
    public DocumentState(int id) {
        this.id = id;
    }
    public DocumentState(int id, String name, Integer priority, Integer groupState) {
       this.id = id;
       this.name = name;
       this.priority = priority;
       this.groupState = groupState;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    
    @Column(name="GROUP_STATE")
    public Integer getGroupState() {
        return this.groupState;
    }
    
    public void setGroupState(Integer groupState) {
        this.groupState = groupState;
    }




}


