package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentTypes generated by hbm2java
 */
@Entity
@Table(name="DOCUMENT_TYPES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class DocumentTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer groupCustomerId;

    public DocumentTypes() {
    }

	
    public DocumentTypes(int id) {
        this.id = id;
    }
    public DocumentTypes(int id, String name, Integer groupCustomerId) {
       this.id = id;
       this.name = name;
       this.groupCustomerId = groupCustomerId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="GROUP_CUSTOMER_ID")
    public Integer getGroupCustomerId() {
        return this.groupCustomerId;
    }
    
    public void setGroupCustomerId(Integer groupCustomerId) {
        this.groupCustomerId = groupCustomerId;
    }




}


