package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentCheckSheet generated by hbm2java
 */
@Entity
@Table(name="DOCUMENT_CHECK_SHEET"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class DocumentCheckSheet  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer termId;
     private Integer stateId;
     private Integer createdBy;
     private Date created;

    public DocumentCheckSheet() {
    }

	
    public DocumentCheckSheet(int id) {
        this.id = id;
    }
    public DocumentCheckSheet(int id, Integer projectId, Integer termId, Integer stateId, Integer createdBy, Date created) {
       this.id = id;
       this.projectId = projectId;
       this.termId = termId;
       this.stateId = stateId;
       this.createdBy = createdBy;
       this.created = created;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="TERM_ID")
    public Integer getTermId() {
        return this.termId;
    }
    
    public void setTermId(Integer termId) {
        this.termId = termId;
    }

    
    @Column(name="STATE_ID")
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


