package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupPrivileges generated by hbm2java
 */
@Entity
@Table(name="GROUP_PRIVILEGES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class GroupPrivileges  implements java.io.Serializable {


     private int id;
     private Integer privilegeId;
     private Integer groupId;

    public GroupPrivileges() {
    }

	
    public GroupPrivileges(int id) {
        this.id = id;
    }
    public GroupPrivileges(int id, Integer privilegeId, Integer groupId) {
       this.id = id;
       this.privilegeId = privilegeId;
       this.groupId = groupId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PRIVILEGE_ID")
    public Integer getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    
    @Column(name="GROUP_ID")
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }




}


