package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="GROUPS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Groups  implements java.io.Serializable {


     private int id;
     private String name;
     private Date created;
     private Date modified;
     private Integer parentId;
     private Integer departementId;

    public Groups() {
    }

	
    public Groups(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Groups(int id, String name, Date created, Date modified, Integer parentId, Integer departementId) {
       this.id = id;
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.parentId = parentId;
       this.departementId = departementId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="PARENT_ID")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="DEPARTEMENT_ID")
    public Integer getDepartementId() {
        return this.departementId;
    }
    
    public void setDepartementId(Integer departementId) {
        this.departementId = departementId;
    }




}


