package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="INVOICE"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Invoice  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer poNo;
     private String noInvoice;
     private Integer nilaiInvoice;
     private Integer nilaiProyeksiPembayaran;
     private Date tanggalPembayaran;
     private Integer nilaiPembayaran;
     private String remark;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modified;

    public Invoice() {
    }

	
    public Invoice(int id) {
        this.id = id;
    }
    public Invoice(int id, Integer projectId, Integer poNo, String noInvoice, Integer nilaiInvoice, Integer nilaiProyeksiPembayaran, Date tanggalPembayaran, Integer nilaiPembayaran, String remark, Integer userCreated, Integer userModified, Date created, Date modified) {
       this.id = id;
       this.projectId = projectId;
       this.poNo = poNo;
       this.noInvoice = noInvoice;
       this.nilaiInvoice = nilaiInvoice;
       this.nilaiProyeksiPembayaran = nilaiProyeksiPembayaran;
       this.tanggalPembayaran = tanggalPembayaran;
       this.nilaiPembayaran = nilaiPembayaran;
       this.remark = remark;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="PO_NO")
    public Integer getPoNo() {
        return this.poNo;
    }
    
    public void setPoNo(Integer poNo) {
        this.poNo = poNo;
    }

    
    @Column(name="NO_INVOICE", length=12)
    public String getNoInvoice() {
        return this.noInvoice;
    }
    
    public void setNoInvoice(String noInvoice) {
        this.noInvoice = noInvoice;
    }

    
    @Column(name="NILAI_INVOICE")
    public Integer getNilaiInvoice() {
        return this.nilaiInvoice;
    }
    
    public void setNilaiInvoice(Integer nilaiInvoice) {
        this.nilaiInvoice = nilaiInvoice;
    }

    
    @Column(name="NILAI_PROYEKSI_PEMBAYARAN")
    public Integer getNilaiProyeksiPembayaran() {
        return this.nilaiProyeksiPembayaran;
    }
    
    public void setNilaiProyeksiPembayaran(Integer nilaiProyeksiPembayaran) {
        this.nilaiProyeksiPembayaran = nilaiProyeksiPembayaran;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_PEMBAYARAN", length=23)
    public Date getTanggalPembayaran() {
        return this.tanggalPembayaran;
    }
    
    public void setTanggalPembayaran(Date tanggalPembayaran) {
        this.tanggalPembayaran = tanggalPembayaran;
    }

    
    @Column(name="NILAI_PEMBAYARAN")
    public Integer getNilaiPembayaran() {
        return this.nilaiPembayaran;
    }
    
    public void setNilaiPembayaran(Integer nilaiPembayaran) {
        this.nilaiPembayaran = nilaiPembayaran;
    }

    
    @Column(name="REMARK", length=50)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


