package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InvoicePercent generated by hbm2java
 */
@Entity
@Table(name="INVOICE_PERCENT"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class InvoicePercent  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer percentInvoice1;
     private Integer percentInvoice2;
     private Integer percentInvoice3;
     private Integer percentInvoice4;
     private Integer invoice1Req;
     private Integer invoice2Req;
     private Integer invoice3Req;
     private Integer invoice4Req;

    public InvoicePercent() {
    }

	
    public InvoicePercent(int id) {
        this.id = id;
    }
    public InvoicePercent(int id, String name, Integer percentInvoice1, Integer percentInvoice2, Integer percentInvoice3, Integer percentInvoice4, Integer invoice1Req, Integer invoice2Req, Integer invoice3Req, Integer invoice4Req) {
       this.id = id;
       this.name = name;
       this.percentInvoice1 = percentInvoice1;
       this.percentInvoice2 = percentInvoice2;
       this.percentInvoice3 = percentInvoice3;
       this.percentInvoice4 = percentInvoice4;
       this.invoice1Req = invoice1Req;
       this.invoice2Req = invoice2Req;
       this.invoice3Req = invoice3Req;
       this.invoice4Req = invoice4Req;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PERCENT_INVOICE1")
    public Integer getPercentInvoice1() {
        return this.percentInvoice1;
    }
    
    public void setPercentInvoice1(Integer percentInvoice1) {
        this.percentInvoice1 = percentInvoice1;
    }

    
    @Column(name="PERCENT_INVOICE2")
    public Integer getPercentInvoice2() {
        return this.percentInvoice2;
    }
    
    public void setPercentInvoice2(Integer percentInvoice2) {
        this.percentInvoice2 = percentInvoice2;
    }

    
    @Column(name="PERCENT_INVOICE3")
    public Integer getPercentInvoice3() {
        return this.percentInvoice3;
    }
    
    public void setPercentInvoice3(Integer percentInvoice3) {
        this.percentInvoice3 = percentInvoice3;
    }

    
    @Column(name="PERCENT_INVOICE4")
    public Integer getPercentInvoice4() {
        return this.percentInvoice4;
    }
    
    public void setPercentInvoice4(Integer percentInvoice4) {
        this.percentInvoice4 = percentInvoice4;
    }

    
    @Column(name="INVOICE1_REQ")
    public Integer getInvoice1Req() {
        return this.invoice1Req;
    }
    
    public void setInvoice1Req(Integer invoice1Req) {
        this.invoice1Req = invoice1Req;
    }

    
    @Column(name="INVOICE2_REQ")
    public Integer getInvoice2Req() {
        return this.invoice2Req;
    }
    
    public void setInvoice2Req(Integer invoice2Req) {
        this.invoice2Req = invoice2Req;
    }

    
    @Column(name="INVOICE3_REQ")
    public Integer getInvoice3Req() {
        return this.invoice3Req;
    }
    
    public void setInvoice3Req(Integer invoice3Req) {
        this.invoice3Req = invoice3Req;
    }

    
    @Column(name="INVOICE4_REQ")
    public Integer getInvoice4Req() {
        return this.invoice4Req;
    }
    
    public void setInvoice4Req(Integer invoice4Req) {
        this.invoice4Req = invoice4Req;
    }




}


