package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogActivity generated by hbm2java
 */
@Entity
@Table(name="LOG_ACTIVITY"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class LogActivity  implements java.io.Serializable {


     private int id;
     private Integer userId;
     private String activity;
     private Date created;

    public LogActivity() {
    }

	
    public LogActivity(int id) {
        this.id = id;
    }
    public LogActivity(int id, Integer userId, String activity, Date created) {
       this.id = id;
       this.userId = userId;
       this.activity = activity;
       this.created = created;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="ACTIVITY", length=100)
    public String getActivity() {
        return this.activity;
    }
    
    public void setActivity(String activity) {
        this.activity = activity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


