package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogMailed generated by hbm2java
 */
@Entity
@Table(name="LOG_MAILED"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class LogMailed  implements java.io.Serializable {


     private int id;
     private Integer userId;
     private String attentionTo;
     private String message;
     private Integer retries;
     private Date dateCreated;

    public LogMailed() {
    }

	
    public LogMailed(int id) {
        this.id = id;
    }
    public LogMailed(int id, Integer userId, String attentionTo, String message, Integer retries, Date dateCreated) {
       this.id = id;
       this.userId = userId;
       this.attentionTo = attentionTo;
       this.message = message;
       this.retries = retries;
       this.dateCreated = dateCreated;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="ATTENTION_TO", length=8000)
    public String getAttentionTo() {
        return this.attentionTo;
    }
    
    public void setAttentionTo(String attentionTo) {
        this.attentionTo = attentionTo;
    }

    
    @Column(name="MESSAGE", length=3000)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="RETRIES")
    public Integer getRetries() {
        return this.retries;
    }
    
    public void setRetries(Integer retries) {
        this.retries = retries;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CREATED", length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


