package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ManagerAssign generated by hbm2java
 */
@Entity
@Table(name="MANAGER_ASSIGN"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ManagerAssign  implements java.io.Serializable {


     private int id;
     private String managerName;
     private String jabatan;

    public ManagerAssign() {
    }

	
    public ManagerAssign(int id) {
        this.id = id;
    }
    public ManagerAssign(int id, String managerName, String jabatan) {
       this.id = id;
       this.managerName = managerName;
       this.jabatan = jabatan;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="MANAGER_NAME", length=1000)
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    
    @Column(name="JABATAN", length=100)
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }




}


