package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mandor generated by hbm2java
 */
@Entity
@Table(name="MANDOR"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Mandor  implements java.io.Serializable {


     private int id;
     private String nama;
     private String alamat;
     private String telp;
     private String email;
     private Integer status;
     private Date created;
     private String noKtp;
     private Integer mandorRate;
     private String namaAlias;
     private String namaKoordinator;
     private String npwp;
     private String handphone1;
     private String handphone2;
     private String handphoneDarurat;
     private Integer team;
     private String lokasiAkhir;
     private String prasetiaMandorId;

    public Mandor() {
    }

	
    public Mandor(int id) {
        this.id = id;
    }
    public Mandor(int id, String nama, String alamat, String telp, String email, Integer status, Date created, String noKtp, Integer mandorRate, String namaAlias, String namaKoordinator, String npwp, String handphone1, String handphone2, String handphoneDarurat, Integer team, String lokasiAkhir, String prasetiaMandorId) {
       this.id = id;
       this.nama = nama;
       this.alamat = alamat;
       this.telp = telp;
       this.email = email;
       this.status = status;
       this.created = created;
       this.noKtp = noKtp;
       this.mandorRate = mandorRate;
       this.namaAlias = namaAlias;
       this.namaKoordinator = namaKoordinator;
       this.npwp = npwp;
       this.handphone1 = handphone1;
       this.handphone2 = handphone2;
       this.handphoneDarurat = handphoneDarurat;
       this.team = team;
       this.lokasiAkhir = lokasiAkhir;
       this.prasetiaMandorId = prasetiaMandorId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAMA", length=50)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="ALAMAT", length=200)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="TELP", length=20)
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="NO_KTP", length=20)
    public String getNoKtp() {
        return this.noKtp;
    }
    
    public void setNoKtp(String noKtp) {
        this.noKtp = noKtp;
    }

    
    @Column(name="MANDOR_RATE")
    public Integer getMandorRate() {
        return this.mandorRate;
    }
    
    public void setMandorRate(Integer mandorRate) {
        this.mandorRate = mandorRate;
    }

    
    @Column(name="NAMA_ALIAS", length=50)
    public String getNamaAlias() {
        return this.namaAlias;
    }
    
    public void setNamaAlias(String namaAlias) {
        this.namaAlias = namaAlias;
    }

    
    @Column(name="NAMA_KOORDINATOR", length=50)
    public String getNamaKoordinator() {
        return this.namaKoordinator;
    }
    
    public void setNamaKoordinator(String namaKoordinator) {
        this.namaKoordinator = namaKoordinator;
    }

    
    @Column(name="NPWP", length=100)
    public String getNpwp() {
        return this.npwp;
    }
    
    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }

    
    @Column(name="HANDPHONE1", length=20)
    public String getHandphone1() {
        return this.handphone1;
    }
    
    public void setHandphone1(String handphone1) {
        this.handphone1 = handphone1;
    }

    
    @Column(name="HANDPHONE2", length=20)
    public String getHandphone2() {
        return this.handphone2;
    }
    
    public void setHandphone2(String handphone2) {
        this.handphone2 = handphone2;
    }

    
    @Column(name="HANDPHONE_DARURAT", length=20)
    public String getHandphoneDarurat() {
        return this.handphoneDarurat;
    }
    
    public void setHandphoneDarurat(String handphoneDarurat) {
        this.handphoneDarurat = handphoneDarurat;
    }

    
    @Column(name="TEAM")
    public Integer getTeam() {
        return this.team;
    }
    
    public void setTeam(Integer team) {
        this.team = team;
    }

    
    @Column(name="LOKASI_AKHIR", length=100)
    public String getLokasiAkhir() {
        return this.lokasiAkhir;
    }
    
    public void setLokasiAkhir(String lokasiAkhir) {
        this.lokasiAkhir = lokasiAkhir;
    }

    
    @Column(name="PRASETIA_MANDOR_ID", length=20)
    public String getPrasetiaMandorId() {
        return this.prasetiaMandorId;
    }
    
    public void setPrasetiaMandorId(String prasetiaMandorId) {
        this.prasetiaMandorId = prasetiaMandorId;
    }




}


