package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandorNotes generated by hbm2java
 */
@Entity
@Table(name="MANDOR_NOTES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class MandorNotes  implements java.io.Serializable {


     private int id;
     private Integer mandorId;
     private String notes;
     private Integer userId;
     private Date created;

    public MandorNotes() {
    }

	
    public MandorNotes(int id) {
        this.id = id;
    }
    public MandorNotes(int id, Integer mandorId, String notes, Integer userId, Date created) {
       this.id = id;
       this.mandorId = mandorId;
       this.notes = notes;
       this.userId = userId;
       this.created = created;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="MANDOR_ID")
    public Integer getMandorId() {
        return this.mandorId;
    }
    
    public void setMandorId(Integer mandorId) {
        this.mandorId = mandorId;
    }

    
    @Column(name="NOTES", length=1000)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


