package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandorProject generated by hbm2java
 */
@Entity
@Table(name="MANDOR_PROJECT"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class MandorProject  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer mandorId;
     private Date start;
     private Date planDone;
     private Date actualDone;
     private Integer mandorCandidateId;
     private Integer verifikasi;
     private Integer mandorTypeId;

    public MandorProject() {
    }

	
    public MandorProject(int id) {
        this.id = id;
    }
    public MandorProject(int id, Integer projectId, Integer mandorId, Date start, Date planDone, Date actualDone, Integer mandorCandidateId, Integer verifikasi, Integer mandorTypeId) {
       this.id = id;
       this.projectId = projectId;
       this.mandorId = mandorId;
       this.start = start;
       this.planDone = planDone;
       this.actualDone = actualDone;
       this.mandorCandidateId = mandorCandidateId;
       this.verifikasi = verifikasi;
       this.mandorTypeId = mandorTypeId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="MANDOR_ID")
    public Integer getMandorId() {
        return this.mandorId;
    }
    
    public void setMandorId(Integer mandorId) {
        this.mandorId = mandorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START", length=23)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DONE", length=23)
    public Date getPlanDone() {
        return this.planDone;
    }
    
    public void setPlanDone(Date planDone) {
        this.planDone = planDone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_DONE", length=23)
    public Date getActualDone() {
        return this.actualDone;
    }
    
    public void setActualDone(Date actualDone) {
        this.actualDone = actualDone;
    }

    
    @Column(name="MANDOR_CANDIDATE_ID")
    public Integer getMandorCandidateId() {
        return this.mandorCandidateId;
    }
    
    public void setMandorCandidateId(Integer mandorCandidateId) {
        this.mandorCandidateId = mandorCandidateId;
    }

    
    @Column(name="VERIFIKASI")
    public Integer getVerifikasi() {
        return this.verifikasi;
    }
    
    public void setVerifikasi(Integer verifikasi) {
        this.verifikasi = verifikasi;
    }

    
    @Column(name="MANDOR_TYPE_ID")
    public Integer getMandorTypeId() {
        return this.mandorTypeId;
    }
    
    public void setMandorTypeId(Integer mandorTypeId) {
        this.mandorTypeId = mandorTypeId;
    }




}


