package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandorCandidates generated by hbm2java
 */
@Entity
@Table(name="MANDOR_CANDIDATES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class MandorCandidates  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer mandorId;
     private Integer mandorUsed;
     private Integer userCreated;
     private Date created;
     private Date modified;
     private Integer status;
     private Date start;
     private Date planDone;
     private String remark;
     private String remarkPurchasing;
     private Integer reqId;
     private Integer mandorMaterialId;
     private Integer sipil;
     private Integer ereksi;
     private Integer me;
     private Integer typePenunjukan;
     private Integer mandorProjectIdReplacement;

    public MandorCandidates() {
    }

	
    public MandorCandidates(int id) {
        this.id = id;
    }
    public MandorCandidates(int id, Integer projectId, Integer mandorId, Integer mandorUsed, Integer userCreated, Date created, Date modified, Integer status, Date start, Date planDone, String remark, String remarkPurchasing, Integer reqId, Integer mandorMaterialId, Integer sipil, Integer ereksi, Integer me, Integer typePenunjukan, Integer mandorProjectIdReplacement) {
       this.id = id;
       this.projectId = projectId;
       this.mandorId = mandorId;
       this.mandorUsed = mandorUsed;
       this.userCreated = userCreated;
       this.created = created;
       this.modified = modified;
       this.status = status;
       this.start = start;
       this.planDone = planDone;
       this.remark = remark;
       this.remarkPurchasing = remarkPurchasing;
       this.reqId = reqId;
       this.mandorMaterialId = mandorMaterialId;
       this.sipil = sipil;
       this.ereksi = ereksi;
       this.me = me;
       this.typePenunjukan = typePenunjukan;
       this.mandorProjectIdReplacement = mandorProjectIdReplacement;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="MANDOR_ID")
    public Integer getMandorId() {
        return this.mandorId;
    }
    
    public void setMandorId(Integer mandorId) {
        this.mandorId = mandorId;
    }

    
    @Column(name="MANDOR_USED")
    public Integer getMandorUsed() {
        return this.mandorUsed;
    }
    
    public void setMandorUsed(Integer mandorUsed) {
        this.mandorUsed = mandorUsed;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START", length=23)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DONE", length=23)
    public Date getPlanDone() {
        return this.planDone;
    }
    
    public void setPlanDone(Date planDone) {
        this.planDone = planDone;
    }

    
    @Column(name="REMARK", length=1000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="REMARK_PURCHASING", length=1000)
    public String getRemarkPurchasing() {
        return this.remarkPurchasing;
    }
    
    public void setRemarkPurchasing(String remarkPurchasing) {
        this.remarkPurchasing = remarkPurchasing;
    }

    
    @Column(name="REQ_ID")
    public Integer getReqId() {
        return this.reqId;
    }
    
    public void setReqId(Integer reqId) {
        this.reqId = reqId;
    }

    
    @Column(name="MANDOR_MATERIAL_ID")
    public Integer getMandorMaterialId() {
        return this.mandorMaterialId;
    }
    
    public void setMandorMaterialId(Integer mandorMaterialId) {
        this.mandorMaterialId = mandorMaterialId;
    }

    
    @Column(name="SIPIL")
    public Integer getSipil() {
        return this.sipil;
    }
    
    public void setSipil(Integer sipil) {
        this.sipil = sipil;
    }

    
    @Column(name="EREKSI")
    public Integer getEreksi() {
        return this.ereksi;
    }
    
    public void setEreksi(Integer ereksi) {
        this.ereksi = ereksi;
    }

    
    @Column(name="ME")
    public Integer getMe() {
        return this.me;
    }
    
    public void setMe(Integer me) {
        this.me = me;
    }

    
    @Column(name="TYPE_PENUNJUKAN")
    public Integer getTypePenunjukan() {
        return this.typePenunjukan;
    }
    
    public void setTypePenunjukan(Integer typePenunjukan) {
        this.typePenunjukan = typePenunjukan;
    }

    
    @Column(name="MANDOR_PROJECT_ID_REPLACEMENT")
    public Integer getMandorProjectIdReplacement() {
        return this.mandorProjectIdReplacement;
    }
    
    public void setMandorProjectIdReplacement(Integer mandorProjectIdReplacement) {
        this.mandorProjectIdReplacement = mandorProjectIdReplacement;
    }




}


