package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MandorHistory generated by hbm2java
 */
@Entity
@Table(name="MANDOR_HISTORY"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class MandorHistory  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer mandorId;
     private Date dateCreated;

    public MandorHistory() {
    }

	
    public MandorHistory(int id) {
        this.id = id;
    }
    public MandorHistory(int id, Integer projectId, Integer mandorId, Date dateCreated) {
       this.id = id;
       this.projectId = projectId;
       this.mandorId = mandorId;
       this.dateCreated = dateCreated;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="MANDOR_ID")
    public Integer getMandorId() {
        return this.mandorId;
    }
    
    public void setMandorId(Integer mandorId) {
        this.mandorId = mandorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CREATED", length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


