package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MasterId generated by hbm2java
 */
@Entity
@Table(name="MASTER_ID"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class MasterId  implements java.io.Serializable {


     private int id;
     private String pref;
     private String suff;
     private String midf;
     private String type;
     private String dept;
     private Integer month;
     private Integer year;
     private Long inc;
     private Long start;
     private Long limit;

    public MasterId() {
    }

	
    public MasterId(int id) {
        this.id = id;
    }
    public MasterId(int id, String pref, String suff, String midf, String type, String dept, Integer month, Integer year, Long inc, Long start, Long limit) {
       this.id = id;
       this.pref = pref;
       this.suff = suff;
       this.midf = midf;
       this.type = type;
       this.dept = dept;
       this.month = month;
       this.year = year;
       this.inc = inc;
       this.start = start;
       this.limit = limit;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PREF", length=50)
    public String getPref() {
        return this.pref;
    }
    
    public void setPref(String pref) {
        this.pref = pref;
    }

    
    @Column(name="SUFF", length=50)
    public String getSuff() {
        return this.suff;
    }
    
    public void setSuff(String suff) {
        this.suff = suff;
    }

    
    @Column(name="MIDF", length=50)
    public String getMidf() {
        return this.midf;
    }
    
    public void setMidf(String midf) {
        this.midf = midf;
    }

    
    @Column(name="TYPE", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="DEPT", length=50)
    public String getDept() {
        return this.dept;
    }
    
    public void setDept(String dept) {
        this.dept = dept;
    }

    
    @Column(name="MONTH")
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }

    
    @Column(name="YEAR")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    
    @Column(name="INC")
    public Long getInc() {
        return this.inc;
    }
    
    public void setInc(Long inc) {
        this.inc = inc;
    }

    
    @Column(name="START")
    public Long getStart() {
        return this.start;
    }
    
    public void setStart(Long start) {
        this.start = start;
    }

    
    @Column(name="LIMIT")
    public Long getLimit() {
        return this.limit;
    }
    
    public void setLimit(Long limit) {
        this.limit = limit;
    }




}


