package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OpenerpConstructionProject generated by hbm2java
 */
@Entity
@Table(name="OPENERP_CONSTRUCTION_PROJECT"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class OpenerpConstructionProject  implements java.io.Serializable {


     private int id;
     private Integer constructionProjectId;
     private String actionType;
     private Integer siteTypeId;
     private Integer operatorId;
     private String name;
     private Date tanggalDimulai;
     private Integer siteId;
     private Date tanggalSuratTugas;
     private Integer active;
     private Date tanggalSelesai;
     private Date tanggalTargetRfi;

    public OpenerpConstructionProject() {
    }

	
    public OpenerpConstructionProject(int id) {
        this.id = id;
    }
    public OpenerpConstructionProject(int id, Integer constructionProjectId, String actionType, Integer siteTypeId, Integer operatorId, String name, Date tanggalDimulai, Integer siteId, Date tanggalSuratTugas, Integer active, Date tanggalSelesai, Date tanggalTargetRfi) {
       this.id = id;
       this.constructionProjectId = constructionProjectId;
       this.actionType = actionType;
       this.siteTypeId = siteTypeId;
       this.operatorId = operatorId;
       this.name = name;
       this.tanggalDimulai = tanggalDimulai;
       this.siteId = siteId;
       this.tanggalSuratTugas = tanggalSuratTugas;
       this.active = active;
       this.tanggalSelesai = tanggalSelesai;
       this.tanggalTargetRfi = tanggalTargetRfi;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CONSTRUCTION_PROJECT_ID")
    public Integer getConstructionProjectId() {
        return this.constructionProjectId;
    }
    
    public void setConstructionProjectId(Integer constructionProjectId) {
        this.constructionProjectId = constructionProjectId;
    }

    
    @Column(name="ACTION_TYPE", length=2)
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    
    @Column(name="SITE_TYPE_ID")
    public Integer getSiteTypeId() {
        return this.siteTypeId;
    }
    
    public void setSiteTypeId(Integer siteTypeId) {
        this.siteTypeId = siteTypeId;
    }

    
    @Column(name="OPERATOR_ID")
    public Integer getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    
    @Column(name="NAME", length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_DIMULAI", length=23)
    public Date getTanggalDimulai() {
        return this.tanggalDimulai;
    }
    
    public void setTanggalDimulai(Date tanggalDimulai) {
        this.tanggalDimulai = tanggalDimulai;
    }

    
    @Column(name="SITE_ID")
    public Integer getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_SURAT_TUGAS", length=23)
    public Date getTanggalSuratTugas() {
        return this.tanggalSuratTugas;
    }
    
    public void setTanggalSuratTugas(Date tanggalSuratTugas) {
        this.tanggalSuratTugas = tanggalSuratTugas;
    }

    
    @Column(name="ACTIVE")
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_SELESAI", length=23)
    public Date getTanggalSelesai() {
        return this.tanggalSelesai;
    }
    
    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_TARGET_RFI", length=23)
    public Date getTanggalTargetRfi() {
        return this.tanggalTargetRfi;
    }
    
    public void setTanggalTargetRfi(Date tanggalTargetRfi) {
        this.tanggalTargetRfi = tanggalTargetRfi;
    }




}


