package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PengeluaranSite generated by hbm2java
 */
@Entity
@Table(name="PENGELUARAN_SITE"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class PengeluaranSite  implements java.io.Serializable {


     private int id;
     private Integer departementId;
     private Date tanggalPengeluaran;
     private Integer budgetSourceId;
     private String jenisPengeluaran;
     private BigDecimal pengeluaran;
     private BigDecimal penerimaan;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;
     private Integer siteId;
     private Integer miscWorkId;
     private Date tanggalPengajuan;
     private BigDecimal jumlahPengajuan;

    public PengeluaranSite() {
    }

	
    public PengeluaranSite(int id) {
        this.id = id;
    }
    public PengeluaranSite(int id, Integer departementId, Date tanggalPengeluaran, Integer budgetSourceId, String jenisPengeluaran, BigDecimal pengeluaran, BigDecimal penerimaan, Date created, Date modified, Integer userCreated, Integer userModified, Integer siteId, Integer miscWorkId, Date tanggalPengajuan, BigDecimal jumlahPengajuan) {
       this.id = id;
       this.departementId = departementId;
       this.tanggalPengeluaran = tanggalPengeluaran;
       this.budgetSourceId = budgetSourceId;
       this.jenisPengeluaran = jenisPengeluaran;
       this.pengeluaran = pengeluaran;
       this.penerimaan = penerimaan;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.siteId = siteId;
       this.miscWorkId = miscWorkId;
       this.tanggalPengajuan = tanggalPengajuan;
       this.jumlahPengajuan = jumlahPengajuan;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="DEPARTEMENT_ID")
    public Integer getDepartementId() {
        return this.departementId;
    }
    
    public void setDepartementId(Integer departementId) {
        this.departementId = departementId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_PENGELUARAN", length=23)
    public Date getTanggalPengeluaran() {
        return this.tanggalPengeluaran;
    }
    
    public void setTanggalPengeluaran(Date tanggalPengeluaran) {
        this.tanggalPengeluaran = tanggalPengeluaran;
    }

    
    @Column(name="BUDGET_SOURCE_ID")
    public Integer getBudgetSourceId() {
        return this.budgetSourceId;
    }
    
    public void setBudgetSourceId(Integer budgetSourceId) {
        this.budgetSourceId = budgetSourceId;
    }

    
    @Column(name="JENIS_PENGELUARAN", length=500)
    public String getJenisPengeluaran() {
        return this.jenisPengeluaran;
    }
    
    public void setJenisPengeluaran(String jenisPengeluaran) {
        this.jenisPengeluaran = jenisPengeluaran;
    }

    
    @Column(name="PENGELUARAN", precision=12)
    public BigDecimal getPengeluaran() {
        return this.pengeluaran;
    }
    
    public void setPengeluaran(BigDecimal pengeluaran) {
        this.pengeluaran = pengeluaran;
    }

    
    @Column(name="PENERIMAAN", precision=12)
    public BigDecimal getPenerimaan() {
        return this.penerimaan;
    }
    
    public void setPenerimaan(BigDecimal penerimaan) {
        this.penerimaan = penerimaan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    
    @Column(name="SITE_ID")
    public Integer getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    
    @Column(name="MISC_WORK_ID")
    public Integer getMiscWorkId() {
        return this.miscWorkId;
    }
    
    public void setMiscWorkId(Integer miscWorkId) {
        this.miscWorkId = miscWorkId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_PENGAJUAN", length=23)
    public Date getTanggalPengajuan() {
        return this.tanggalPengajuan;
    }
    
    public void setTanggalPengajuan(Date tanggalPengajuan) {
        this.tanggalPengajuan = tanggalPengajuan;
    }

    
    @Column(name="JUMLAH_PENGAJUAN", precision=12)
    public BigDecimal getJumlahPengajuan() {
        return this.jumlahPengajuan;
    }
    
    public void setJumlahPengajuan(BigDecimal jumlahPengajuan) {
        this.jumlahPengajuan = jumlahPengajuan;
    }




}


