package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoProjects generated by hbm2java
 */
@Entity
@Table(name="PO_PROJECTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class PoProjects  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private String noPo;
     private BigDecimal nilaiPo;
     private BigDecimal nilaiProyek;
     private BigDecimal nilaiProyekPpn;
     private String status;
     private String remark;
     private Date tanggalPo;
     private Integer percentInvoice1;
     private Integer percentInvoice2;
     private Integer percentInvoice3;
     private Integer percentInvoice4;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modified;
     private Integer invoiceReq1;
     private Integer invoiceReq2;
     private Integer invoiceReq3;
     private Integer invoiceReq4;

    public PoProjects() {
    }

	
    public PoProjects(int id) {
        this.id = id;
    }
    public PoProjects(int id, Integer projectId, String noPo, BigDecimal nilaiPo, BigDecimal nilaiProyek, BigDecimal nilaiProyekPpn, String status, String remark, Date tanggalPo, Integer percentInvoice1, Integer percentInvoice2, Integer percentInvoice3, Integer percentInvoice4, Integer userCreated, Integer userModified, Date created, Date modified, Integer invoiceReq1, Integer invoiceReq2, Integer invoiceReq3, Integer invoiceReq4) {
       this.id = id;
       this.projectId = projectId;
       this.noPo = noPo;
       this.nilaiPo = nilaiPo;
       this.nilaiProyek = nilaiProyek;
       this.nilaiProyekPpn = nilaiProyekPpn;
       this.status = status;
       this.remark = remark;
       this.tanggalPo = tanggalPo;
       this.percentInvoice1 = percentInvoice1;
       this.percentInvoice2 = percentInvoice2;
       this.percentInvoice3 = percentInvoice3;
       this.percentInvoice4 = percentInvoice4;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modified = modified;
       this.invoiceReq1 = invoiceReq1;
       this.invoiceReq2 = invoiceReq2;
       this.invoiceReq3 = invoiceReq3;
       this.invoiceReq4 = invoiceReq4;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="NO_PO", length=50)
    public String getNoPo() {
        return this.noPo;
    }
    
    public void setNoPo(String noPo) {
        this.noPo = noPo;
    }

    
    @Column(name="NILAI_PO", precision=12)
    public BigDecimal getNilaiPo() {
        return this.nilaiPo;
    }
    
    public void setNilaiPo(BigDecimal nilaiPo) {
        this.nilaiPo = nilaiPo;
    }

    
    @Column(name="NILAI_PROYEK", precision=12)
    public BigDecimal getNilaiProyek() {
        return this.nilaiProyek;
    }
    
    public void setNilaiProyek(BigDecimal nilaiProyek) {
        this.nilaiProyek = nilaiProyek;
    }

    
    @Column(name="NILAI_PROYEK_PPN", precision=12)
    public BigDecimal getNilaiProyekPpn() {
        return this.nilaiProyekPpn;
    }
    
    public void setNilaiProyekPpn(BigDecimal nilaiProyekPpn) {
        this.nilaiProyekPpn = nilaiProyekPpn;
    }

    
    @Column(name="STATUS", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_PO", length=23)
    public Date getTanggalPo() {
        return this.tanggalPo;
    }
    
    public void setTanggalPo(Date tanggalPo) {
        this.tanggalPo = tanggalPo;
    }

    
    @Column(name="PERCENT_INVOICE1")
    public Integer getPercentInvoice1() {
        return this.percentInvoice1;
    }
    
    public void setPercentInvoice1(Integer percentInvoice1) {
        this.percentInvoice1 = percentInvoice1;
    }

    
    @Column(name="PERCENT_INVOICE2")
    public Integer getPercentInvoice2() {
        return this.percentInvoice2;
    }
    
    public void setPercentInvoice2(Integer percentInvoice2) {
        this.percentInvoice2 = percentInvoice2;
    }

    
    @Column(name="PERCENT_INVOICE3")
    public Integer getPercentInvoice3() {
        return this.percentInvoice3;
    }
    
    public void setPercentInvoice3(Integer percentInvoice3) {
        this.percentInvoice3 = percentInvoice3;
    }

    
    @Column(name="PERCENT_INVOICE4")
    public Integer getPercentInvoice4() {
        return this.percentInvoice4;
    }
    
    public void setPercentInvoice4(Integer percentInvoice4) {
        this.percentInvoice4 = percentInvoice4;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="INVOICE_REQ1")
    public Integer getInvoiceReq1() {
        return this.invoiceReq1;
    }
    
    public void setInvoiceReq1(Integer invoiceReq1) {
        this.invoiceReq1 = invoiceReq1;
    }

    
    @Column(name="INVOICE_REQ2")
    public Integer getInvoiceReq2() {
        return this.invoiceReq2;
    }
    
    public void setInvoiceReq2(Integer invoiceReq2) {
        this.invoiceReq2 = invoiceReq2;
    }

    
    @Column(name="INVOICE_REQ3")
    public Integer getInvoiceReq3() {
        return this.invoiceReq3;
    }
    
    public void setInvoiceReq3(Integer invoiceReq3) {
        this.invoiceReq3 = invoiceReq3;
    }

    
    @Column(name="INVOICE_REQ4")
    public Integer getInvoiceReq4() {
        return this.invoiceReq4;
    }
    
    public void setInvoiceReq4(Integer invoiceReq4) {
        this.invoiceReq4 = invoiceReq4;
    }




}


