package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Privilages generated by hbm2java
 */
@Entity
@Table(name="PRIVILAGES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Privilages  implements java.io.Serializable {


     private int id;
     private Integer controllerId;
     private Integer moduleId;

    public Privilages() {
    }

	
    public Privilages(int id) {
        this.id = id;
    }
    public Privilages(int id, Integer controllerId, Integer moduleId) {
       this.id = id;
       this.controllerId = controllerId;
       this.moduleId = moduleId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CONTROLLER_ID")
    public Integer getControllerId() {
        return this.controllerId;
    }
    
    public void setControllerId(Integer controllerId) {
        this.controllerId = controllerId;
    }

    
    @Column(name="MODULE_ID")
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }




}


