package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProgressDetails generated by hbm2java
 */
@Entity
@Table(name="PROGRESS_DETAILS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID", "PROGRESS_TYPE_ID"}) 
)
public class ProgressDetails  implements java.io.Serializable {


     private int id;
     private int progressTypeId;
     private String name;
     private int bobot;
     private int priority;

    public ProgressDetails() {
    }

    public ProgressDetails(int id, int progressTypeId, String name, int bobot, int priority) {
       this.id = id;
       this.progressTypeId = progressTypeId;
       this.name = name;
       this.bobot = bobot;
       this.priority = priority;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROGRESS_TYPE_ID", nullable=false)
    public int getProgressTypeId() {
        return this.progressTypeId;
    }
    
    public void setProgressTypeId(int progressTypeId) {
        this.progressTypeId = progressTypeId;
    }

    
    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="BOBOT", nullable=false)
    public int getBobot() {
        return this.bobot;
    }
    
    public void setBobot(int bobot) {
        this.bobot = bobot;
    }

    
    @Column(name="PRIORITY", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }




}


