package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProgressTypes generated by hbm2java
 */
@Entity
@Table(name="PROGRESS_TYPES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProgressTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private int priority;

    public ProgressTypes() {
    }

    public ProgressTypes(int id, String name, int priority) {
       this.id = id;
       this.name = name;
       this.priority = priority;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PRIORITY", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }




}


