package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectDocument generated by hbm2java
 */
@Entity
@Table(name="PROJECT_DOCUMENT"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectDocument  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private String name;
     private String filePath;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modified;
     private String remark;
     private Integer documentBinderTypeId;
     private Integer documentVersion;
     private BigDecimal nilaiDocument;
     private Integer documentStatusId;

    public ProjectDocument() {
    }

	
    public ProjectDocument(int id) {
        this.id = id;
    }
    public ProjectDocument(int id, Integer projectId, String name, String filePath, Integer userCreated, Integer userModified, Date created, Date modified, String remark, Integer documentBinderTypeId, Integer documentVersion, BigDecimal nilaiDocument, Integer documentStatusId) {
       this.id = id;
       this.projectId = projectId;
       this.name = name;
       this.filePath = filePath;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modified = modified;
       this.remark = remark;
       this.documentBinderTypeId = documentBinderTypeId;
       this.documentVersion = documentVersion;
       this.nilaiDocument = nilaiDocument;
       this.documentStatusId = documentStatusId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="NAME", length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="FILE_PATH", length=500)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="REMARK", length=500)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="DOCUMENT_BINDER_TYPE_ID")
    public Integer getDocumentBinderTypeId() {
        return this.documentBinderTypeId;
    }
    
    public void setDocumentBinderTypeId(Integer documentBinderTypeId) {
        this.documentBinderTypeId = documentBinderTypeId;
    }

    
    @Column(name="DOCUMENT_VERSION")
    public Integer getDocumentVersion() {
        return this.documentVersion;
    }
    
    public void setDocumentVersion(Integer documentVersion) {
        this.documentVersion = documentVersion;
    }

    
    @Column(name="NILAI_DOCUMENT", precision=12)
    public BigDecimal getNilaiDocument() {
        return this.nilaiDocument;
    }
    
    public void setNilaiDocument(BigDecimal nilaiDocument) {
        this.nilaiDocument = nilaiDocument;
    }

    
    @Column(name="DOCUMENT_STATUS_ID")
    public Integer getDocumentStatusId() {
        return this.documentStatusId;
    }
    
    public void setDocumentStatusId(Integer documentStatusId) {
        this.documentStatusId = documentStatusId;
    }




}


