package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectInvoices generated by hbm2java
 */
@Entity
@Table(name="PROJECT_INVOICES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectInvoices  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer term;
     private Integer invoiceTypeId;
     private BigDecimal nilaiInvoice;
     private BigDecimal nilaiPembayaran;
     private String noInvoice;
     private Date tanggalInvoice;
     private Date tanggalPembayaran;
     private String remark;
     private BigDecimal nilaiProyeksiPembayaran;
     private Integer invoiceStatusId;
     private String nomorBuktiPotong;

    public ProjectInvoices() {
    }

	
    public ProjectInvoices(int id) {
        this.id = id;
    }
    public ProjectInvoices(int id, Integer projectId, Integer term, Integer invoiceTypeId, BigDecimal nilaiInvoice, BigDecimal nilaiPembayaran, String noInvoice, Date tanggalInvoice, Date tanggalPembayaran, String remark, BigDecimal nilaiProyeksiPembayaran, Integer invoiceStatusId, String nomorBuktiPotong) {
       this.id = id;
       this.projectId = projectId;
       this.term = term;
       this.invoiceTypeId = invoiceTypeId;
       this.nilaiInvoice = nilaiInvoice;
       this.nilaiPembayaran = nilaiPembayaran;
       this.noInvoice = noInvoice;
       this.tanggalInvoice = tanggalInvoice;
       this.tanggalPembayaran = tanggalPembayaran;
       this.remark = remark;
       this.nilaiProyeksiPembayaran = nilaiProyeksiPembayaran;
       this.invoiceStatusId = invoiceStatusId;
       this.nomorBuktiPotong = nomorBuktiPotong;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="TERM")
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }

    
    @Column(name="INVOICE_TYPE_ID")
    public Integer getInvoiceTypeId() {
        return this.invoiceTypeId;
    }
    
    public void setInvoiceTypeId(Integer invoiceTypeId) {
        this.invoiceTypeId = invoiceTypeId;
    }

    
    @Column(name="NILAI_INVOICE", precision=12)
    public BigDecimal getNilaiInvoice() {
        return this.nilaiInvoice;
    }
    
    public void setNilaiInvoice(BigDecimal nilaiInvoice) {
        this.nilaiInvoice = nilaiInvoice;
    }

    
    @Column(name="NILAI_PEMBAYARAN", precision=12)
    public BigDecimal getNilaiPembayaran() {
        return this.nilaiPembayaran;
    }
    
    public void setNilaiPembayaran(BigDecimal nilaiPembayaran) {
        this.nilaiPembayaran = nilaiPembayaran;
    }

    
    @Column(name="NO_INVOICE", length=100)
    public String getNoInvoice() {
        return this.noInvoice;
    }
    
    public void setNoInvoice(String noInvoice) {
        this.noInvoice = noInvoice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_INVOICE", length=23)
    public Date getTanggalInvoice() {
        return this.tanggalInvoice;
    }
    
    public void setTanggalInvoice(Date tanggalInvoice) {
        this.tanggalInvoice = tanggalInvoice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_PEMBAYARAN", length=23)
    public Date getTanggalPembayaran() {
        return this.tanggalPembayaran;
    }
    
    public void setTanggalPembayaran(Date tanggalPembayaran) {
        this.tanggalPembayaran = tanggalPembayaran;
    }

    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="NILAI_PROYEKSI_PEMBAYARAN", precision=12)
    public BigDecimal getNilaiProyeksiPembayaran() {
        return this.nilaiProyeksiPembayaran;
    }
    
    public void setNilaiProyeksiPembayaran(BigDecimal nilaiProyeksiPembayaran) {
        this.nilaiProyeksiPembayaran = nilaiProyeksiPembayaran;
    }

    
    @Column(name="INVOICE_STATUS_ID")
    public Integer getInvoiceStatusId() {
        return this.invoiceStatusId;
    }
    
    public void setInvoiceStatusId(Integer invoiceStatusId) {
        this.invoiceStatusId = invoiceStatusId;
    }

    
    @Column(name="NOMOR_BUKTI_POTONG", length=100)
    public String getNomorBuktiPotong() {
        return this.nomorBuktiPotong;
    }
    
    public void setNomorBuktiPotong(String nomorBuktiPotong) {
        this.nomorBuktiPotong = nomorBuktiPotong;
    }




}


