package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectProblemsId generated by hbm2java
 */
@Embeddable
public class ProjectProblemsId  implements java.io.Serializable {


     private int id;
     private int projectId;

    public ProjectProblemsId() {
    }

    public ProjectProblemsId(int id, int projectId) {
       this.id = id;
       this.projectId = projectId;
    }
   


    @Column(name="ID", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="PROJECT_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectProblemsId) ) return false;
		 ProjectProblemsId castOther = ( ProjectProblemsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getProjectId()==castOther.getProjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getProjectId();
         return result;
   }   


}


