package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name="PROJECTS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Projects  implements java.io.Serializable {


     private int id;
     private Integer siteId;
     private String prasetiaProjectId;
     private Integer siteProjectTypeId;
     private Integer projectManagerId;
     private Integer customerContactId;
     private Integer statusId;
     private Date tanggalSuratTugas;
     private Date tanggalDimulai;
     private Date tanggalTargetRfi;
     private Date tanggalSelesai;
     private Integer presentase;
     private String remark;
     private Integer projectOfficerId;
     private Integer poId;
     private Integer boqId;
     private Integer userCreated;
     private Integer userModified;
     private Date created;
     private Date modified;
     private Integer operatorId;
     private Integer mandorId;
     private Date tanggalTargetRfiPrasetia;
     private String dayaPln;
     private String pabrikasiTower;
     private Integer shelterTypeId;
     private Integer pph;
     private Integer miscWorksId;
     private Integer plnStatus;
     private String noMemoInternal;
     private Integer addworkTypeId;
     private Date meetingDrm;
     private Date tanggalFakturPajak;

    public Projects() {
    }

	
    public Projects(int id) {
        this.id = id;
    }
    public Projects(int id, Integer siteId, String prasetiaProjectId, Integer siteProjectTypeId, Integer projectManagerId, Integer customerContactId, Integer statusId, Date tanggalSuratTugas, Date tanggalDimulai, Date tanggalTargetRfi, Date tanggalSelesai, Integer presentase, String remark, Integer projectOfficerId, Integer poId, Integer boqId, Integer userCreated, Integer userModified, Date created, Date modified, Integer operatorId, Integer mandorId, Date tanggalTargetRfiPrasetia, String dayaPln, String pabrikasiTower, Integer shelterTypeId, Integer pph, Integer miscWorksId, Integer plnStatus, String noMemoInternal, Integer addworkTypeId, Date meetingDrm, Date tanggalFakturPajak) {
       this.id = id;
       this.siteId = siteId;
       this.prasetiaProjectId = prasetiaProjectId;
       this.siteProjectTypeId = siteProjectTypeId;
       this.projectManagerId = projectManagerId;
       this.customerContactId = customerContactId;
       this.statusId = statusId;
       this.tanggalSuratTugas = tanggalSuratTugas;
       this.tanggalDimulai = tanggalDimulai;
       this.tanggalTargetRfi = tanggalTargetRfi;
       this.tanggalSelesai = tanggalSelesai;
       this.presentase = presentase;
       this.remark = remark;
       this.projectOfficerId = projectOfficerId;
       this.poId = poId;
       this.boqId = boqId;
       this.userCreated = userCreated;
       this.userModified = userModified;
       this.created = created;
       this.modified = modified;
       this.operatorId = operatorId;
       this.mandorId = mandorId;
       this.tanggalTargetRfiPrasetia = tanggalTargetRfiPrasetia;
       this.dayaPln = dayaPln;
       this.pabrikasiTower = pabrikasiTower;
       this.shelterTypeId = shelterTypeId;
       this.pph = pph;
       this.miscWorksId = miscWorksId;
       this.plnStatus = plnStatus;
       this.noMemoInternal = noMemoInternal;
       this.addworkTypeId = addworkTypeId;
       this.meetingDrm = meetingDrm;
       this.tanggalFakturPajak = tanggalFakturPajak;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="SITE_ID")
    public Integer getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    
    @Column(name="PRASETIA_PROJECT_ID", length=12)
    public String getPrasetiaProjectId() {
        return this.prasetiaProjectId;
    }
    
    public void setPrasetiaProjectId(String prasetiaProjectId) {
        this.prasetiaProjectId = prasetiaProjectId;
    }

    
    @Column(name="SITE_PROJECT_TYPE_ID")
    public Integer getSiteProjectTypeId() {
        return this.siteProjectTypeId;
    }
    
    public void setSiteProjectTypeId(Integer siteProjectTypeId) {
        this.siteProjectTypeId = siteProjectTypeId;
    }

    
    @Column(name="PROJECT_MANAGER_ID")
    public Integer getProjectManagerId() {
        return this.projectManagerId;
    }
    
    public void setProjectManagerId(Integer projectManagerId) {
        this.projectManagerId = projectManagerId;
    }

    
    @Column(name="CUSTOMER_CONTACT_ID")
    public Integer getCustomerContactId() {
        return this.customerContactId;
    }
    
    public void setCustomerContactId(Integer customerContactId) {
        this.customerContactId = customerContactId;
    }

    
    @Column(name="STATUS_ID")
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_SURAT_TUGAS", length=23)
    public Date getTanggalSuratTugas() {
        return this.tanggalSuratTugas;
    }
    
    public void setTanggalSuratTugas(Date tanggalSuratTugas) {
        this.tanggalSuratTugas = tanggalSuratTugas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_DIMULAI", length=23)
    public Date getTanggalDimulai() {
        return this.tanggalDimulai;
    }
    
    public void setTanggalDimulai(Date tanggalDimulai) {
        this.tanggalDimulai = tanggalDimulai;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_TARGET_RFI", length=23)
    public Date getTanggalTargetRfi() {
        return this.tanggalTargetRfi;
    }
    
    public void setTanggalTargetRfi(Date tanggalTargetRfi) {
        this.tanggalTargetRfi = tanggalTargetRfi;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_SELESAI", length=23)
    public Date getTanggalSelesai() {
        return this.tanggalSelesai;
    }
    
    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }

    
    @Column(name="PRESENTASE")
    public Integer getPresentase() {
        return this.presentase;
    }
    
    public void setPresentase(Integer presentase) {
        this.presentase = presentase;
    }

    
    @Column(name="REMARK", length=250)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="PROJECT_OFFICER_ID")
    public Integer getProjectOfficerId() {
        return this.projectOfficerId;
    }
    
    public void setProjectOfficerId(Integer projectOfficerId) {
        this.projectOfficerId = projectOfficerId;
    }

    
    @Column(name="PO_ID")
    public Integer getPoId() {
        return this.poId;
    }
    
    public void setPoId(Integer poId) {
        this.poId = poId;
    }

    
    @Column(name="BOQ_ID")
    public Integer getBoqId() {
        return this.boqId;
    }
    
    public void setBoqId(Integer boqId) {
        this.boqId = boqId;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="OPERATOR_ID")
    public Integer getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    
    @Column(name="MANDOR_ID")
    public Integer getMandorId() {
        return this.mandorId;
    }
    
    public void setMandorId(Integer mandorId) {
        this.mandorId = mandorId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_TARGET_RFI_PRASETIA", length=23)
    public Date getTanggalTargetRfiPrasetia() {
        return this.tanggalTargetRfiPrasetia;
    }
    
    public void setTanggalTargetRfiPrasetia(Date tanggalTargetRfiPrasetia) {
        this.tanggalTargetRfiPrasetia = tanggalTargetRfiPrasetia;
    }

    
    @Column(name="DAYA_PLN", length=50)
    public String getDayaPln() {
        return this.dayaPln;
    }
    
    public void setDayaPln(String dayaPln) {
        this.dayaPln = dayaPln;
    }

    
    @Column(name="PABRIKASI_TOWER", length=50)
    public String getPabrikasiTower() {
        return this.pabrikasiTower;
    }
    
    public void setPabrikasiTower(String pabrikasiTower) {
        this.pabrikasiTower = pabrikasiTower;
    }

    
    @Column(name="SHELTER_TYPE_ID")
    public Integer getShelterTypeId() {
        return this.shelterTypeId;
    }
    
    public void setShelterTypeId(Integer shelterTypeId) {
        this.shelterTypeId = shelterTypeId;
    }

    
    @Column(name="PPH")
    public Integer getPph() {
        return this.pph;
    }
    
    public void setPph(Integer pph) {
        this.pph = pph;
    }

    
    @Column(name="MISC_WORKS_ID")
    public Integer getMiscWorksId() {
        return this.miscWorksId;
    }
    
    public void setMiscWorksId(Integer miscWorksId) {
        this.miscWorksId = miscWorksId;
    }

    
    @Column(name="PLN_STATUS")
    public Integer getPlnStatus() {
        return this.plnStatus;
    }
    
    public void setPlnStatus(Integer plnStatus) {
        this.plnStatus = plnStatus;
    }

    
    @Column(name="NO_MEMO_INTERNAL", length=100)
    public String getNoMemoInternal() {
        return this.noMemoInternal;
    }
    
    public void setNoMemoInternal(String noMemoInternal) {
        this.noMemoInternal = noMemoInternal;
    }

    
    @Column(name="ADDWORK_TYPE_ID")
    public Integer getAddworkTypeId() {
        return this.addworkTypeId;
    }
    
    public void setAddworkTypeId(Integer addworkTypeId) {
        this.addworkTypeId = addworkTypeId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MEETING_DRM", length=23)
    public Date getMeetingDrm() {
        return this.meetingDrm;
    }
    
    public void setMeetingDrm(Date meetingDrm) {
        this.meetingDrm = meetingDrm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TANGGAL_FAKTUR_PAJAK", length=23)
    public Date getTanggalFakturPajak() {
        return this.tanggalFakturPajak;
    }
    
    public void setTanggalFakturPajak(Date tanggalFakturPajak) {
        this.tanggalFakturPajak = tanggalFakturPajak;
    }




}


