package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectProblems generated by hbm2java
 */
@Entity
@Table(name="PROJECT_PROBLEMS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectProblems  implements java.io.Serializable {


     private ProjectProblemsId id;
     private String ticketNo;
     private String problemDetail;
     private String howToSolve;
     private String countermeasure;
     private Date dateOccured;
     private Date dateSolved;
     private Integer userCreated;
     private Integer status;
     private Date lastResponse;
     private Date created;
     private Date modified;
     private Integer problemTypeId;

    public ProjectProblems() {
    }

	
    public ProjectProblems(ProjectProblemsId id, String problemDetail, Date created, Date modified) {
        this.id = id;
        this.problemDetail = problemDetail;
        this.created = created;
        this.modified = modified;
    }
    public ProjectProblems(ProjectProblemsId id, String ticketNo, String problemDetail, String howToSolve, String countermeasure, Date dateOccured, Date dateSolved, Integer userCreated, Integer status, Date lastResponse, Date created, Date modified, Integer problemTypeId) {
       this.id = id;
       this.ticketNo = ticketNo;
       this.problemDetail = problemDetail;
       this.howToSolve = howToSolve;
       this.countermeasure = countermeasure;
       this.dateOccured = dateOccured;
       this.dateSolved = dateSolved;
       this.userCreated = userCreated;
       this.status = status;
       this.lastResponse = lastResponse;
       this.created = created;
       this.modified = modified;
       this.problemTypeId = problemTypeId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="projectId", column=@Column(name="PROJECT_ID", nullable=false) ) } )
    public ProjectProblemsId getId() {
        return this.id;
    }
    
    public void setId(ProjectProblemsId id) {
        this.id = id;
    }

    
    @Column(name="TICKET_NO", length=15)
    public String getTicketNo() {
        return this.ticketNo;
    }
    
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo;
    }

    
    @Column(name="PROBLEM_DETAIL", nullable=false, length=250)
    public String getProblemDetail() {
        return this.problemDetail;
    }
    
    public void setProblemDetail(String problemDetail) {
        this.problemDetail = problemDetail;
    }

    
    @Column(name="HOW_TO_SOLVE")
    public String getHowToSolve() {
        return this.howToSolve;
    }
    
    public void setHowToSolve(String howToSolve) {
        this.howToSolve = howToSolve;
    }

    
    @Column(name="COUNTERMEASURE", length=250)
    public String getCountermeasure() {
        return this.countermeasure;
    }
    
    public void setCountermeasure(String countermeasure) {
        this.countermeasure = countermeasure;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_OCCURED", length=23)
    public Date getDateOccured() {
        return this.dateOccured;
    }
    
    public void setDateOccured(Date dateOccured) {
        this.dateOccured = dateOccured;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_SOLVED", length=23)
    public Date getDateSolved() {
        return this.dateSolved;
    }
    
    public void setDateSolved(Date dateSolved) {
        this.dateSolved = dateSolved;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="STATUS")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_RESPONSE", length=23)
    public Date getLastResponse() {
        return this.lastResponse;
    }
    
    public void setLastResponse(Date lastResponse) {
        this.lastResponse = lastResponse;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", nullable=false, length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="PROBLEM_TYPE_ID")
    public Integer getProblemTypeId() {
        return this.problemTypeId;
    }
    
    public void setProblemTypeId(Integer problemTypeId) {
        this.problemTypeId = problemTypeId;
    }




}


