package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectBudget generated by hbm2java
 */
@Entity
@Table(name="PROJECT_BUDGET"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectBudget  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private String noBudget;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public ProjectBudget() {
    }

	
    public ProjectBudget(int id) {
        this.id = id;
    }
    public ProjectBudget(int id, Integer projectId, String noBudget, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.id = id;
       this.projectId = projectId;
       this.noBudget = noBudget;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="NO_BUDGET", length=50)
    public String getNoBudget() {
        return this.noBudget;
    }
    
    public void setNoBudget(String noBudget) {
        this.noBudget = noBudget;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


