package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectJustifikasi generated by hbm2java
 */
@Entity
@Table(name="PROJECT_JUSTIFIKASI"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectJustifikasi  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer progressDetailId;
     private Date dateStart;
     private Date dateFinish;
     private String remark;
     private Integer userCreated;
     private Date dateCreated;
     private Integer statusId;

    public ProjectJustifikasi() {
    }

	
    public ProjectJustifikasi(int id) {
        this.id = id;
    }
    public ProjectJustifikasi(int id, Integer projectId, Integer progressDetailId, Date dateStart, Date dateFinish, String remark, Integer userCreated, Date dateCreated, Integer statusId) {
       this.id = id;
       this.projectId = projectId;
       this.progressDetailId = progressDetailId;
       this.dateStart = dateStart;
       this.dateFinish = dateFinish;
       this.remark = remark;
       this.userCreated = userCreated;
       this.dateCreated = dateCreated;
       this.statusId = statusId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="PROGRESS_DETAIL_ID")
    public Integer getProgressDetailId() {
        return this.progressDetailId;
    }
    
    public void setProgressDetailId(Integer progressDetailId) {
        this.progressDetailId = progressDetailId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_START", length=23)
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_FINISH", length=23)
    public Date getDateFinish() {
        return this.dateFinish;
    }
    
    public void setDateFinish(Date dateFinish) {
        this.dateFinish = dateFinish;
    }

    
    @Column(name="REMARK", length=3000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CREATED", length=23)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="STATUS_ID")
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }




}


