package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectBudgetDetail generated by hbm2java
 */
@Entity
@Table(name="PROJECT_BUDGET_DETAIL"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class ProjectBudgetDetail  implements java.io.Serializable {


     private int id;
     private Integer projectBudgetId;
     private String item;
     private String satuan;
     private Integer qty;
     private BigDecimal hargaSatuanPo;
     private BigDecimal hargaSatuanAktual;
     private BigDecimal totalHargaPo;
     private BigDecimal totalHargaAktual;
     private Integer state;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public ProjectBudgetDetail() {
    }

	
    public ProjectBudgetDetail(int id) {
        this.id = id;
    }
    public ProjectBudgetDetail(int id, Integer projectBudgetId, String item, String satuan, Integer qty, BigDecimal hargaSatuanPo, BigDecimal hargaSatuanAktual, BigDecimal totalHargaPo, BigDecimal totalHargaAktual, Integer state, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.id = id;
       this.projectBudgetId = projectBudgetId;
       this.item = item;
       this.satuan = satuan;
       this.qty = qty;
       this.hargaSatuanPo = hargaSatuanPo;
       this.hargaSatuanAktual = hargaSatuanAktual;
       this.totalHargaPo = totalHargaPo;
       this.totalHargaAktual = totalHargaAktual;
       this.state = state;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_BUDGET_ID")
    public Integer getProjectBudgetId() {
        return this.projectBudgetId;
    }
    
    public void setProjectBudgetId(Integer projectBudgetId) {
        this.projectBudgetId = projectBudgetId;
    }

    
    @Column(name="ITEM", length=300)
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }

    
    @Column(name="SATUAN", length=30)
    public String getSatuan() {
        return this.satuan;
    }
    
    public void setSatuan(String satuan) {
        this.satuan = satuan;
    }

    
    @Column(name="QTY")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="HARGA_SATUAN_PO", precision=12)
    public BigDecimal getHargaSatuanPo() {
        return this.hargaSatuanPo;
    }
    
    public void setHargaSatuanPo(BigDecimal hargaSatuanPo) {
        this.hargaSatuanPo = hargaSatuanPo;
    }

    
    @Column(name="HARGA_SATUAN_AKTUAL", precision=12)
    public BigDecimal getHargaSatuanAktual() {
        return this.hargaSatuanAktual;
    }
    
    public void setHargaSatuanAktual(BigDecimal hargaSatuanAktual) {
        this.hargaSatuanAktual = hargaSatuanAktual;
    }

    
    @Column(name="TOTAL_HARGA_PO", precision=12)
    public BigDecimal getTotalHargaPo() {
        return this.totalHargaPo;
    }
    
    public void setTotalHargaPo(BigDecimal totalHargaPo) {
        this.totalHargaPo = totalHargaPo;
    }

    
    @Column(name="TOTAL_HARGA_AKTUAL", precision=12)
    public BigDecimal getTotalHargaAktual() {
        return this.totalHargaAktual;
    }
    
    public void setTotalHargaAktual(BigDecimal totalHargaAktual) {
        this.totalHargaAktual = totalHargaAktual;
    }

    
    @Column(name="STATE")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="USER_CREATED")
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }

    
    @Column(name="USER_MODIFIED")
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


