package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provinces generated by hbm2java
 */
@Entity
@Table(name="PROVINCES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Provinces  implements java.io.Serializable {


     private int id;
     private int islandId;
     private String name;
     private String name1;

    public Provinces() {
    }

	
    public Provinces(int id, int islandId, String name) {
        this.id = id;
        this.islandId = islandId;
        this.name = name;
    }
    public Provinces(int id, int islandId, String name, String name1) {
       this.id = id;
       this.islandId = islandId;
       this.name = name;
       this.name1 = name1;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ISLAND_ID", nullable=false)
    public int getIslandId() {
        return this.islandId;
    }
    
    public void setIslandId(int islandId) {
        this.islandId = islandId;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME1", length=50)
    public String getName1() {
        return this.name1;
    }
    
    public void setName1(String name1) {
        this.name1 = name1;
    }




}


