package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PrStatus generated by hbm2java
 */
@Entity
@Table(name="PR_STATUS"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class PrStatus  implements java.io.Serializable {


     private int projectId;
     private Integer me;
     private Integer civil;
     private Integer gdl;

    public PrStatus() {
    }

	
    public PrStatus(int projectId) {
        this.projectId = projectId;
    }
    public PrStatus(int projectId, Integer me, Integer civil, Integer gdl) {
       this.projectId = projectId;
       this.me = me;
       this.civil = civil;
       this.gdl = gdl;
    }
   
     @Id 

    
    @Column(name="PROJECT_ID", unique=true, nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="ME")
    public Integer getMe() {
        return this.me;
    }
    
    public void setMe(Integer me) {
        this.me = me;
    }

    
    @Column(name="CIVIL")
    public Integer getCivil() {
        return this.civil;
    }
    
    public void setCivil(Integer civil) {
        this.civil = civil;
    }

    
    @Column(name="GDL")
    public Integer getGdl() {
        return this.gdl;
    }
    
    public void setGdl(Integer gdl) {
        this.gdl = gdl;
    }




}


