package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rab generated by hbm2java
 */
@Entity
@Table(name="RAB"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Rab  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private String noRab;
     private Integer nilaiRab;
     private String remark;
     private Date created;
     private Date modified;
     private Date tglRab;

    public Rab() {
    }

	
    public Rab(int id) {
        this.id = id;
    }
    public Rab(int id, Integer projectId, String noRab, Integer nilaiRab, String remark, Date created, Date modified, Date tglRab) {
       this.id = id;
       this.projectId = projectId;
       this.noRab = noRab;
       this.nilaiRab = nilaiRab;
       this.remark = remark;
       this.created = created;
       this.modified = modified;
       this.tglRab = tglRab;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="NO_RAB", length=25)
    public String getNoRab() {
        return this.noRab;
    }
    
    public void setNoRab(String noRab) {
        this.noRab = noRab;
    }

    
    @Column(name="NILAI_RAB")
    public Integer getNilaiRab() {
        return this.nilaiRab;
    }
    
    public void setNilaiRab(Integer nilaiRab) {
        this.nilaiRab = nilaiRab;
    }

    
    @Column(name="REMARK")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TGL_RAB", length=23)
    public Date getTglRab() {
        return this.tglRab;
    }
    
    public void setTglRab(Date tglRab) {
        this.tglRab = tglRab;
    }




}


