package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SiteTypeProgresses generated by hbm2java
 */
@Entity
@Table(name="SITE_TYPE_PROGRESSES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ID", "SITE_TYPE_ID", "PROGRESS_DETAIL_ID"}) 
)
public class SiteTypeProgresses  implements java.io.Serializable {


     private int id;
     private int siteTypeId;
     private int progressDetailId;
     private Integer workDays;
     private Integer planDays;
     private Integer groupCustomerId;
     private Integer siteTypeProgressVersion;

    public SiteTypeProgresses() {
    }

	
    public SiteTypeProgresses(int id, int siteTypeId, int progressDetailId) {
        this.id = id;
        this.siteTypeId = siteTypeId;
        this.progressDetailId = progressDetailId;
    }
    public SiteTypeProgresses(int id, int siteTypeId, int progressDetailId, Integer workDays, Integer planDays, Integer groupCustomerId, Integer siteTypeProgressVersion) {
       this.id = id;
       this.siteTypeId = siteTypeId;
       this.progressDetailId = progressDetailId;
       this.workDays = workDays;
       this.planDays = planDays;
       this.groupCustomerId = groupCustomerId;
       this.siteTypeProgressVersion = siteTypeProgressVersion;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="SITE_TYPE_ID", nullable=false)
    public int getSiteTypeId() {
        return this.siteTypeId;
    }
    
    public void setSiteTypeId(int siteTypeId) {
        this.siteTypeId = siteTypeId;
    }

    
    @Column(name="PROGRESS_DETAIL_ID", nullable=false)
    public int getProgressDetailId() {
        return this.progressDetailId;
    }
    
    public void setProgressDetailId(int progressDetailId) {
        this.progressDetailId = progressDetailId;
    }

    
    @Column(name="WORK_DAYS")
    public Integer getWorkDays() {
        return this.workDays;
    }
    
    public void setWorkDays(Integer workDays) {
        this.workDays = workDays;
    }

    
    @Column(name="PLAN_DAYS")
    public Integer getPlanDays() {
        return this.planDays;
    }
    
    public void setPlanDays(Integer planDays) {
        this.planDays = planDays;
    }

    
    @Column(name="GROUP_CUSTOMER_ID")
    public Integer getGroupCustomerId() {
        return this.groupCustomerId;
    }
    
    public void setGroupCustomerId(Integer groupCustomerId) {
        this.groupCustomerId = groupCustomerId;
    }

    
    @Column(name="SITE_TYPE_PROGRESS_VERSION")
    public Integer getSiteTypeProgressVersion() {
        return this.siteTypeProgressVersion;
    }
    
    public void setSiteTypeProgressVersion(Integer siteTypeProgressVersion) {
        this.siteTypeProgressVersion = siteTypeProgressVersion;
    }




}


