package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SiteTypeStatuses generated by hbm2java
 */
@Entity
@Table(name="SITE_TYPE_STATUSES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class SiteTypeStatuses  implements java.io.Serializable {


     private int id;
     private int statusId;
     private int priority;
     private Integer siteTypeId;

    public SiteTypeStatuses() {
    }

	
    public SiteTypeStatuses(int id, int statusId, int priority) {
        this.id = id;
        this.statusId = statusId;
        this.priority = priority;
    }
    public SiteTypeStatuses(int id, int statusId, int priority, Integer siteTypeId) {
       this.id = id;
       this.statusId = statusId;
       this.priority = priority;
       this.siteTypeId = siteTypeId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="STATUS_ID", nullable=false)
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="PRIORITY", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }

    
    @Column(name="SITE_TYPE_ID")
    public Integer getSiteTypeId() {
        return this.siteTypeId;
    }
    
    public void setSiteTypeId(Integer siteTypeId) {
        this.siteTypeId = siteTypeId;
    }




}


