package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SiteTypes generated by hbm2java
 */
@Entity
@Table(name="SITE_TYPES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class SiteTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private String kode;

    public SiteTypes() {
    }

    public SiteTypes(int id, String name, String kode) {
       this.id = id;
       this.name = name;
       this.kode = kode;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="KODE", nullable=false, length=5)
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }




}


