package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiteProgresses generated by hbm2java
 */
@Entity
@Table(name="SITE_PROGRESSES"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class SiteProgresses  implements java.io.Serializable {


     private int id;
     private int projectId;
     private int progressDetailId;
     private Date planStart;
     private Date actualStart;
     private Date planDone;
     private Date actualDone;
     private String description;
     private Date created;
     private Date modified;
     private Integer foto;
     private String remark;

    public SiteProgresses() {
    }

	
    public SiteProgresses(int id, int projectId, int progressDetailId, Date created, Date modified) {
        this.id = id;
        this.projectId = projectId;
        this.progressDetailId = progressDetailId;
        this.created = created;
        this.modified = modified;
    }
    public SiteProgresses(int id, int projectId, int progressDetailId, Date planStart, Date actualStart, Date planDone, Date actualDone, String description, Date created, Date modified, Integer foto, String remark) {
       this.id = id;
       this.projectId = projectId;
       this.progressDetailId = progressDetailId;
       this.planStart = planStart;
       this.actualStart = actualStart;
       this.planDone = planDone;
       this.actualDone = actualDone;
       this.description = description;
       this.created = created;
       this.modified = modified;
       this.foto = foto;
       this.remark = remark;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="PROGRESS_DETAIL_ID", nullable=false)
    public int getProgressDetailId() {
        return this.progressDetailId;
    }
    
    public void setProgressDetailId(int progressDetailId) {
        this.progressDetailId = progressDetailId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_START", length=23)
    public Date getPlanStart() {
        return this.planStart;
    }
    
    public void setPlanStart(Date planStart) {
        this.planStart = planStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_START", length=23)
    public Date getActualStart() {
        return this.actualStart;
    }
    
    public void setActualStart(Date actualStart) {
        this.actualStart = actualStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DONE", length=23)
    public Date getPlanDone() {
        return this.planDone;
    }
    
    public void setPlanDone(Date planDone) {
        this.planDone = planDone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_DONE", length=23)
    public Date getActualDone() {
        return this.actualDone;
    }
    
    public void setActualDone(Date actualDone) {
        this.actualDone = actualDone;
    }

    
    @Column(name="DESCRIPTION", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", nullable=false, length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", nullable=false, length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="FOTO")
    public Integer getFoto() {
        return this.foto;
    }
    
    public void setFoto(Integer foto) {
        this.foto = foto;
    }

    
    @Column(name="REMARK", length=100)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


