package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TermInvoice generated by hbm2java
 */
@Entity
@Table(name="TERM_INVOICE"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class TermInvoice  implements java.io.Serializable {


     private int id;
     private String name;

    public TermInvoice() {
    }

	
    public TermInvoice(int id) {
        this.id = id;
    }
    public TermInvoice(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=5)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


