package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrLogActivityEpm generated by hbm2java
 */
@Entity
@Table(name="TR_LOG_ACTIVITY_EPM"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class TrLogActivityEpm  implements java.io.Serializable {


     private int id;
     private Integer trLogActTypeId;
     private Integer trLogFormId;
     private Date dateAction;
     private Integer userId;

    public TrLogActivityEpm() {
    }

	
    public TrLogActivityEpm(int id) {
        this.id = id;
    }
    public TrLogActivityEpm(int id, Integer trLogActTypeId, Integer trLogFormId, Date dateAction, Integer userId) {
       this.id = id;
       this.trLogActTypeId = trLogActTypeId;
       this.trLogFormId = trLogFormId;
       this.dateAction = dateAction;
       this.userId = userId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="TR_LOG_ACT_TYPE_ID")
    public Integer getTrLogActTypeId() {
        return this.trLogActTypeId;
    }
    
    public void setTrLogActTypeId(Integer trLogActTypeId) {
        this.trLogActTypeId = trLogActTypeId;
    }

    
    @Column(name="TR_LOG_FORM_ID")
    public Integer getTrLogFormId() {
        return this.trLogFormId;
    }
    
    public void setTrLogFormId(Integer trLogFormId) {
        this.trLogFormId = trLogFormId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_ACTION", length=23)
    public Date getDateAction() {
        return this.dateAction;
    }
    
    public void setDateAction(Date dateAction) {
        this.dateAction = dateAction;
    }

    
    @Column(name="USER_ID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


