package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WaspangProject generated by hbm2java
 */
@Entity
@Table(name="WASPANG_PROJECT"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class WaspangProject  implements java.io.Serializable {


     private int id;
     private Integer projectId;
     private Integer waspangId;
     private Date start;
     private Date planDone;
     private Date actualDone;

    public WaspangProject() {
    }

	
    public WaspangProject(int id) {
        this.id = id;
    }
    public WaspangProject(int id, Integer projectId, Integer waspangId, Date start, Date planDone, Date actualDone) {
       this.id = id;
       this.projectId = projectId;
       this.waspangId = waspangId;
       this.start = start;
       this.planDone = planDone;
       this.actualDone = actualDone;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="PROJECT_ID")
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="WASPANG_ID")
    public Integer getWaspangId() {
        return this.waspangId;
    }
    
    public void setWaspangId(Integer waspangId) {
        this.waspangId = waspangId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START", length=23)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DONE", length=23)
    public Date getPlanDone() {
        return this.planDone;
    }
    
    public void setPlanDone(Date planDone) {
        this.planDone = planDone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTUAL_DONE", length=23)
    public Date getActualDone() {
        return this.actualDone;
    }
    
    public void setActualDone(Date actualDone) {
        this.actualDone = actualDone;
    }




}


