package models;
// Generated Mar 27, 2014 2:07:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Waspang generated by hbm2java
 */
@Entity
@Table(name="WASPANG"
    ,schema="dbo"
    ,catalog="PRST001_prod"
)
public class Waspang  implements java.io.Serializable {


     private int id;
     private String name;
     private String phone;
     private String handphone;
     private String email;
     private String alamat;
     private Date created;
     private Date modified;
     private String noKtp;
     private String password;
     private String username;

    public Waspang() {
    }

	
    public Waspang(int id) {
        this.id = id;
    }
    public Waspang(int id, String name, String phone, String handphone, String email, String alamat, Date created, Date modified, String noKtp, String password, String username) {
       this.id = id;
       this.name = name;
       this.phone = phone;
       this.handphone = handphone;
       this.email = email;
       this.alamat = alamat;
       this.created = created;
       this.modified = modified;
       this.noKtp = noKtp;
       this.password = password;
       this.username = username;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="PHONE", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="HANDPHONE", length=20)
    public String getHandphone() {
        return this.handphone;
    }
    
    public void setHandphone(String handphone) {
        this.handphone = handphone;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ALAMAT", length=200)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED", length=23)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    
    @Column(name="NO_KTP", length=20)
    public String getNoKtp() {
        return this.noKtp;
    }
    
    public void setNoKtp(String noKtp) {
        this.noKtp = noKtp;
    }

    
    @Column(name="PASSWORD", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="USERNAME", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


