package datawarga;
// Generated Mar 20, 2014 10:11:04 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Rumah generated by hbm2java
 */
public class Rumah  implements java.io.Serializable {


     private Integer id;
     private Character blokRumah;
     private Integer nomorRumah;
     private Integer kepalaKeluargaId;
     private String telp;
     private String handphone;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public Rumah() {
    }

    public Rumah(Character blokRumah, Integer nomorRumah, Integer kepalaKeluargaId, String telp, String handphone, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.blokRumah = blokRumah;
       this.nomorRumah = nomorRumah;
       this.kepalaKeluargaId = kepalaKeluargaId;
       this.telp = telp;
       this.handphone = handphone;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Character getBlokRumah() {
        return this.blokRumah;
    }
    
    public void setBlokRumah(Character blokRumah) {
        this.blokRumah = blokRumah;
    }
    public Integer getNomorRumah() {
        return this.nomorRumah;
    }
    
    public void setNomorRumah(Integer nomorRumah) {
        this.nomorRumah = nomorRumah;
    }
    public Integer getKepalaKeluargaId() {
        return this.kepalaKeluargaId;
    }
    
    public void setKepalaKeluargaId(Integer kepalaKeluargaId) {
        this.kepalaKeluargaId = kepalaKeluargaId;
    }
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }
    public String getHandphone() {
        return this.handphone;
    }
    
    public void setHandphone(String handphone) {
        this.handphone = handphone;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


