package datawarga;
// Generated Mar 20, 2014 10:11:04 PM by Hibernate Tools 3.6.0



/**
 * StatusKeluarga generated by hbm2java
 */
public class StatusKeluarga  implements java.io.Serializable {


     private Integer id;
     private String name;

    public StatusKeluarga() {
    }

    public StatusKeluarga(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


