package datawarga;
// Generated Mar 20, 2014 10:11:04 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Warga generated by hbm2java
 */
public class Warga  implements java.io.Serializable {


     private Integer id;
     private Integer idRumah;
     private String nama;
     private Integer jenisKelamin;
     private Integer agama;
     private Integer statusPernikahan;
     private Integer statusDalamKeluarga;
     private String handphone;
     private String tempatLahir;
     private Date tanggalLahir;
     private Date created;
     private Date modified;
     private Integer userCreated;
     private Integer userModified;

    public Warga() {
    }

    public Warga(Integer idRumah, String nama, Integer jenisKelamin, Integer agama, Integer statusPernikahan, Integer statusDalamKeluarga, String handphone, String tempatLahir, Date tanggalLahir, Date created, Date modified, Integer userCreated, Integer userModified) {
       this.idRumah = idRumah;
       this.nama = nama;
       this.jenisKelamin = jenisKelamin;
       this.agama = agama;
       this.statusPernikahan = statusPernikahan;
       this.statusDalamKeluarga = statusDalamKeluarga;
       this.handphone = handphone;
       this.tempatLahir = tempatLahir;
       this.tanggalLahir = tanggalLahir;
       this.created = created;
       this.modified = modified;
       this.userCreated = userCreated;
       this.userModified = userModified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdRumah() {
        return this.idRumah;
    }
    
    public void setIdRumah(Integer idRumah) {
        this.idRumah = idRumah;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(Integer jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public Integer getAgama() {
        return this.agama;
    }
    
    public void setAgama(Integer agama) {
        this.agama = agama;
    }
    public Integer getStatusPernikahan() {
        return this.statusPernikahan;
    }
    
    public void setStatusPernikahan(Integer statusPernikahan) {
        this.statusPernikahan = statusPernikahan;
    }
    public Integer getStatusDalamKeluarga() {
        return this.statusDalamKeluarga;
    }
    
    public void setStatusDalamKeluarga(Integer statusDalamKeluarga) {
        this.statusDalamKeluarga = statusDalamKeluarga;
    }
    public String getHandphone() {
        return this.handphone;
    }
    
    public void setHandphone(String handphone) {
        this.handphone = handphone;
    }
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Integer getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }
    public Integer getUserModified() {
        return this.userModified;
    }
    
    public void setUserModified(Integer userModified) {
        this.userModified = userModified;
    }




}


